// Generated by Manus asset storage.
import { restoreThreejsAssets, assetRestoreDiagnostic } from './threejs-asset-restore.mjs'
import { referencedLocalAssets } from './threejs-asset-inputs.mjs'
try {
  const root = process.cwd(), inputs = await referencedLocalAssets(root)
  await restoreThreejsAssets(root, { includeAsset: rel => inputs.has(rel) })
}
catch (error) { console.error(JSON.stringify(assetRestoreDiagnostic(error))); process.exitCode = 1 }
