// Generated by Manus asset storage.
import { createHash } from 'node:crypto'
import { open } from 'node:fs/promises'
import { extname } from 'node:path'
import { brotliCompressSync, constants as zlibConstants } from 'node:zlib'

const MAX_BYTES = 512 * 1024 * 1024
// The ~40 MB engine wasm compresses to ~8 MB but exceeds CloudFront's 10 MB
// automatic-compression limit, so players downloaded it uncompressed. Store it
// brotli-encoded; browsers decode Content-Encoding transparently. The object key
// still names the digest of the original bytes. Quality 5 is within 5% of the
// size of quality 9 at a fraction of the time. Already-compressed pck and media
// gain little and stay unencoded.
export const WASM_CONTENT_ENCODING = 'br'
const WASM_BROTLI_QUALITY = 5
const MIME = { '.glb': 'model/gltf-binary', '.wasm': 'application/wasm', '.pck': 'application/octet-stream', '.png': 'image/png', '.jpg': 'image/jpeg', '.jpeg': 'image/jpeg', '.webp': 'image/webp', '.ogg': 'audio/ogg', '.mp3': 'audio/mpeg', '.ttf': 'font/ttf', '.otf': 'font/otf', '.ttc': 'font/collection', '.otc': 'font/collection', '.gif': 'image/gif', '.svg': 'image/svg+xml', '.wav': 'audio/wav', '.m4a': 'audio/mp4', '.mp4': 'video/mp4', '.webm': 'video/webm', '.woff': 'font/woff', '.woff2': 'font/woff2' }

const STORAGE_FAILURES = {
  storage_not_configured: ['Project storage is not configured', 'Activate the current project runtime environment with a complete MANUS_API_URL/MANUS_API_KEY or BUILT_IN_FORGE_API_URL/BUILT_IN_FORGE_API_KEY pair, then retry.'],
  storage_configuration_conflict: ['Project storage configuration pairs conflict', 'Refresh the current project runtime environment. The incomplete primary configuration disagrees with the compatibility configuration; no fallback was selected.'],
  storage_invalid_endpoint: ['Invalid storage endpoint', 'Refresh the current project runtime environment with a valid HTTPS storage endpoint (HTTP is supported for localhost only).'],
  storage_authorization_failed: ['Storage upload authorization failed', 'Refresh the current project runtime environment for HTTP 401/403; otherwise retry when the storage service is available.'],
  storage_upload_failed: ['Storage upload failed', 'Retry asset synchronization. Already recorded uploads are retained and unchanged files are skipped.'],
}

// Only fixed diagnostics cross the child-process boundary. Provider messages,
// signed URLs and injected environment values are never diagnostic input.
export class StorageError extends Error {
  constructor(code, httpStatus) {
    const safeCode = Object.hasOwn(STORAGE_FAILURES, code) ? code : 'storage_upload_failed'
    const [message, recovery] = STORAGE_FAILURES[safeCode]
    super(message)
    this.code = safeCode
    this.recovery = recovery
    if (Number.isInteger(httpStatus) && httpStatus >= 100 && httpStatus <= 599) this.httpStatus = httpStatus
  }
}

export function storageURL(value) {
  let url
  try { url = new URL(value) } catch { throw new StorageError('storage_invalid_endpoint') }
  const local = ['localhost', '127.0.0.1', '[::1]'].includes(url.hostname)
  if (url.username || url.password || url.hash || (url.protocol !== 'https:' && !(local && url.protocol === 'http:'))) {
    throw new StorageError('storage_invalid_endpoint')
  }
  return url
}

export function storageConfig(env = process.env) {
  const normalizeURL = value => {
    const base = storageURL(value)
    if (base.search) throw new StorageError('storage_invalid_endpoint')
    return base.toString().replace(/\/+$/, '')
  }
  const primary = { url: env.MANUS_API_URL, key: env.MANUS_API_KEY }
  const fallback = { url: env.BUILT_IN_FORGE_API_URL, key: env.BUILT_IN_FORGE_API_KEY }
  // The canonical pair wins, including when authorization later fails. Never
  // retry another project's credentials after a storage request has failed.
  if (primary.url && primary.key) return { url: normalizeURL(primary.url), key: primary.key }
  if (!fallback.url || !fallback.key) throw new StorageError('storage_not_configured')
  const url = normalizeURL(fallback.url)
  // Both names are injected aliases for the same project. A partial canonical
  // alias may use the complete compatibility pair only when its known fields
  // agree. A URL and key are always selected together, never spliced.
  if ((primary.url && normalizeURL(primary.url) !== url) || (primary.key && primary.key !== fallback.key)) {
    throw new StorageError('storage_configuration_conflict')
  }
  return { url, key: fallback.key }
}

export async function uploadGameFile(file, { env = process.env, fetchFn = fetch } = {}) {
  const config = storageConfig(env)
  const extension = extname(file).toLowerCase()
  if (!/^\.[a-z0-9]{1,12}$/.test(extension)) throw new Error('Unsupported storage file extension')
  const font = MIME[extension]?.startsWith('font/')
  const handle = await open(file, 'r')
  let bytes
  try {
    const info = await handle.stat()
    if (!info.isFile() || !Number.isSafeInteger(info.size) || info.size <= 0 || (!font && info.size > MAX_BYTES)) {
      throw new Error('Storage file must be a nonempty regular file; non-font files are limited to 512 MiB')
    }
    bytes = await handle.readFile()
    if ((!font && bytes.length > MAX_BYTES) || bytes.length !== info.size) throw new Error('Storage file changed while reading')
  } finally { await handle.close() }
  const sha256 = createHash('sha256').update(bytes).digest('hex')
  const objectKey = `game/sha256/${sha256}${extension}`
  const presign = new URL('v1/storage/presign/put', `${config.url}/`)
  presign.searchParams.set('path', objectKey)
  let signed
  try {
    const response = await fetchFn(presign, {
      headers: { authorization: `Bearer ${config.key}` },
      redirect: 'error', signal: AbortSignal.timeout(60_000),
    })
    if (!response.ok) throw new StorageError('storage_authorization_failed', response.status)
    const payload = await response.json()
    if (payload.error || typeof payload.url !== 'string') throw new Error('invalid response')
    signed = storageURL(payload.url)
  } catch (error) {
    if (error instanceof StorageError && error.code === 'storage_authorization_failed') throw error
    throw new StorageError('storage_authorization_failed')
  }
  const encoded = extension === '.wasm'
  const body = encoded ? brotliCompressSync(bytes, { params: {
    [zlibConstants.BROTLI_PARAM_QUALITY]: WASM_BROTLI_QUALITY,
    [zlibConstants.BROTLI_PARAM_SIZE_HINT]: bytes.length,
  } }) : bytes
  const headers = { 'content-type': MIME[extension] || 'application/octet-stream' }
  if (encoded) headers['content-encoding'] = WASM_CONTENT_ENCODING
  try {
    const response = await fetchFn(signed, {
      method: 'PUT', body,
      headers,
      redirect: 'error', signal: AbortSignal.timeout(10 * 60_000),
    })
    if (!response.ok) throw new StorageError('storage_upload_failed', response.status)
  } catch (error) {
    if (error instanceof StorageError) throw error
    throw new StorageError('storage_upload_failed')
  }
  return { path: `/manus-storage/${objectKey}`, sha256: `sha256:${sha256}`, size: bytes.length }
}
